### ISSUE TITLE
Fixes with onboarding pages

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#103]
This page requires some fixes.

<img width="666" alt="SCR-20241021-rgli" src="https://github.com/user-attachments/assets/de0f764f-68c8-48c8-ad74-c31a75bccb1f">

**Comment by GabrielChan1** [comment]
Page has been fixed
![Fixed company registration page](https://github.com/user-attachments/assets/6d24a971-ef83-4966-b97a-9cbcfdb1352c)

**Comment by gorkem-bwl** [comment]
Thanks Gabriel. The contents in the middle are too wide (especially the text entry area). Can you please fix it? You can just narrow everything down according to Figma design.

<img width="948" alt="image" src="https://github.com/user-attachments/assets/4ccf9207-aead-4734-b47c-7a0c8d506bcd">
