### ISSUE TITLE
Create tabbed bar component

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#105]
As per the Figma file: https://www.figma.com/design/USQRG7Oacv7uXw8XkTPINq/Style-guide?node-id=253-8140&t=MiataLv7LkzcjQtN-1

**Comment by ergunesra** [comment]
The tabs component was created and applied to the other components.
![tabs_component](https://github.com/user-attachments/assets/fa0f4f4e-5296-4883-af3d-a16d521a7b55)
