### ISSUE TITLE
Revamp my info section

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#106]
The "My info" section of the employee needed a revamp and the [current Figma design](https://www.figma.com/design/GC5nLN8GAXV9NJkzEnDRj3/HRM-app?node-id=2305-16802&t=Z2ad4rXOJ5NuaRwz-1) reflects this.

In this design, instead of one column, there are 3 columns. Some of the inputs have changed its location, and there is another statics "contact information" section added as well. No inputs were removed or added, so this task is merely a redesign.

![image](https://github.com/user-attachments/assets/747c3724-6d1b-4120-b34e-d3d81979f71e)

**Comment by SandipGyawali** [comment]
@gorkem-bwl can work on this issue ??

**Comment by gorkem-bwl** [comment]
Hi Sandip. Please go ahead. Make sure you use MUI components. Once you are done, please attach a video to this issue.

**Comment by SandipGyawali** [comment]
@gorkem-bwl thanks, but i am having trouble to identify in which branch should i contribute to can you mention it please ??

**Comment by olusegunawowole** [comment]
Hi Sandip, You can create a branch for this issue.

**Comment by gorkem-bwl** [comment]
@SandipGyawali just wanted to check here on how things are moving forward. If you could give us a heads up about the progress - that would be great. Thanks!

**Comment by SandipGyawali** [comment]
> @SandipGyawali just wanted to check here on how things are moving forward. If you could give us a heads up about the progress - that would be great. Thanks!

Can you just give the branch that I need to do it, Ii confused from which branch to pull.  I didn't find any thing in the main branch if you can help on this I will complete shortly.
_

**Comment by gorkem-bwl** [comment]
> > @SandipGyawali just wanted to check here on how things are moving forward. If you could give us a heads up about the progress - that would be great. Thanks!
> 
> Can you just give the branch that I need to do it, Ii confused from which branch to pull. I didn't find any thing in the main branch if you can help on this I will complete shortly. _

Please pull from main branch. Can you let me know what you mean by "I didn't find anything in the main branch" ?

**Comment by PranitiV** [comment]
Hi!. I'm looking for an open source project to contribute to. This looks like a good starting place. Can I create a branch, work on this issue and open a PR? @gorkem-bwl 

Thanks!

**Comment by gorkem-bwl** [comment]
> Hi!. I'm looking for an open source project to contribute to. This looks like a good starting place. Can I create a branch, work on this issue and open a PR? @gorkem-bwl
> 
> Thanks!

Yes, please go ahead.

**Comment by gorkem-bwl** [comment]
This one is already done by @olusegunawowole so closing.
