### ISSUE TITLE
Implement email templates

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#23]
Implement email templates for the following actions. This requires writing an HTML template with proper wording/sentences.

**Signup/sign in related**

- [ ] When an HRM manager starts the employee activation process
An email to the employee
- [ ] When a new employee/HR manager signs up (welcome email)
An email to the HRM manager
An email to the employee
- [ ] When employee forgets email
- [ ] Activation email

**HRM application related**

- [ ] When an employee changes job description
An email to the employee
An email to the HRM manager
An email to the employee's manager (if exists) 
- [ ] When an employee leaves the company
An email to the HRM manager
An email to the employee's manager (if exists)
- [ ] When an employee asks for a leave 
An email to the HRM manager
An email to the employee's manager (if exists)
- [ ] When a time off request is created
An email to the HRM manager
An email to the employee
An email to the employee's manager (if exists)
- [ ] When a leave is accepted/denied
An email to the HRM manager
An email to the employee
An email to the employee's manager (if exists)

**Comment by louisv20** [comment]
Is your project open source?

**Comment by gorkem-bwl** [comment]
@louisv20 yes.

**Comment by louisv20** [comment]
I am a new developer but I can attempt to implement these changes. I can start with one html file and submit PR for review?

**Comment by gorkem-bwl** [comment]
Sure, go ahead. Make sure you check other email templates and also honor their licenses (eg use templates with a permissive license) before opening a PR. Note that those emails should be in a template format. They better look good, simple and easy to the eyes.

**Comment by louisv20** [comment]
I've added one email template. It was created with the help of AI so no licensing restrictions. If code is up to par, I can implement the remaining templates.

**Comment by gorkem-bwl** [comment]
Looks good. Go ahead and implement the remaining. Just a note that there might be additional modifications to the templates in the future depending on how the backend will generate them and send.

**Comment by louisv20** [comment]
I've implemented a total of 18 email templates. Please review PR #26

**Comment by gorkem-bwl** [comment]
I have created a design template for this. Can you implement this one in yours? 

<img width="1075" alt="Email design template" src="https://github.com/bluewave-labs/bluewave-hrm/assets/167266851/4795cf6a-5f00-4e26-9aa3-e3be798466e9">

**Comment by louisv20** [comment]
You want that template as a separate html file?

**Comment by zaidi201** [comment]
Yes you can give html file as well

**Comment by louisv20** [comment]
Ok, I will add to PR #26

**Comment by louisv20** [comment]
It's done 👍

**Comment by gorkem-bwl** [comment]
Can you add this styling to your templates @louisv20 ? 

<img width="1075" alt="Email design template" src="https://github.com/bluewave-labs/bluewave-hrm/assets/167266851/a27535a3-3d4e-428f-a475-0f2d3e0aae7e">

Logo: 
![Enthalpy-logo](https://github.com/bluewave-labs/bluewave-hrm/assets/167266851/c9d40d4b-79a7-4ea8-9165-511e01bfc6fa)

**Comment by louisv20** [comment]
I can add logo and button. I'm not sure how to appropriately implement bullet points and lists into the subject matter
![Screenshot (399)](https://github.com/bluewave-labs/bluewave-hrm/assets/163933770/6defc412-e03d-4438-842c-bcb38dc21d00)

**Comment by gorkem-bwl** [comment]
Bullet points and lists are just html elements. Those would be in the template file, and not necessarily in each email.

**Comment by louisv20** [comment]
> Bullet points and lists are just html elements. Those would be in the template file, and not necessarily in each email.

Will something like this work for each email?
![Screenshot (402)](https://github.com/bluewave-labs/bluewave-hrm/assets/163933770/6cadbd35-e219-427f-8d5e-f748b6ccb2b5)

**Comment by gorkem-bwl** [comment]
Yes, that would work for each email. Note that you don't have to use styling if there is no need. That template is given as an example.

**Comment by louisv20** [comment]
> Yes, that would work for each email. Note that you don't have to use styling if there is no need. That template is given as an example.

I've made the necessary changes. Please review to merge.

**Comment by Gol0DRoger** [comment]
Thanks @louisv20  for resolving this issue! 
I want to contribute to this issue with my methodology. Please @gorkem-bwl  allow me to give my solutions.
I'm also familiar with HTML, and javascript. I am happy to answer any follow-up questions.

**Comment by gorkemcetin** [comment]
> Thanks @louisv20 for resolving this issue! I want to contribute to this issue with my methodology. Please @gorkem-bwl allow me to give my solutions. I'm also familiar with HTML, and javascript. I am happy to answer any follow-up questions.

Sure, go ahead Rishab!

**Comment by Gol0DRoger** [comment]
I have created something valuable to this issue, There is a working video file attached to it. I tried my best efficient methodology to the extent of my knowledge.

https://github.com/bluewave-labs/bluewave-hrm/assets/141852484/0483c15f-7668-4099-8c0b-b1115a9140ff

 I look forward to your feedback @gorkemcetin  !

**Comment by gorkem-bwl** [comment]
That looks good, @Gol0DRoger - let me create a Figma design file for this and move from there. It will have tabs on the left for each email, and will separate subject and body as two editors. We also need a list of tags to use here so the end user can know which tags to use (eg. [Company name] or [Last day of the work].

**Comment by Gol0DRoger** [comment]
Great, Let's see. @gorkem-bwl I am not sure if I would be able to execute all of that, but will try.

**Comment by gorkem-bwl** [comment]
Can you also remove all the styling from the templates, and use {{ }} for the placeholders? @Gol0DRoger 

This way the styling is not in the templates and the editor only accepts text as well. Let's get rid of the HTML elements completely.

**Comment by gorkem-bwl** [comment]
Example: 

Dear {{Employee Name}}

We received a request to reset your password. Please click the link below to reset your password:

{{Reset Link}}

If you did not request a password reset, please ignore this email.

If you have any questions, feel free to contact us at {{Support email}}.

Best,
{{Company name}}

**Comment by Gol0DRoger** [comment]
@gorkem-bwl see this one, I executed the changes. No styling/css.
![Screenshot 2024-06-27 163914](https://github.com/bluewave-labs/bluewave-hrm/assets/141852484/c4719516-3ab5-484f-a114-e9a43a543960)

**Comment by gorkem-bwl** [comment]
Yes, better looks like this (each and every of them). Need newlines as well. Make sure it is readable.

**Comment by Gol0DRoger** [comment]
ok fine.

**Comment by Gol0DRoger** [comment]
I have executed all the changes in all templates and added PR #37 . Please review it and get it merged.

https://github.com/bluewave-labs/bluewave-hrm/assets/141852484/ce1f941b-831a-443f-b137-2519238d44ee

@gorkem-bwl

**Comment by gorkem-bwl** [comment]
@bolatein can you come up with a design for this? Each section can be a tab on the left, and contents can go to the right. 

@Gol0DRoger we also need to separate the subject and contents of the email. After @bolatein is done with the design, you need to use our Figma design guidelines to come up with a UI design. After the review, we can merge.

**Comment by Gol0DRoger** [comment]
Fine, I will wait for further updates from your side @gorkem-bwl  @bolatein.Then I will make the required changes.

**Comment by gorkem-bwl** [comment]
Thank you @Gol0DRoger @louisv20 for your contributions here. I created https://github.com/bluewave-labs/bluewave-hrm/issues/57 for MJML templates now and it will be assigned to a developer by @zaidi201 .
