### ISSUE TITLE
Implement time off menus and pages

### ISSUE THREAD

**Issue by GabrielChan1** [bluewave-labs/bluewave-hrm#25]

**Comment by gorkem-bwl** [comment]
Today we had an overview of those pages and it looks like we need a small change. There is now a button, when clicked, will enable the user to set hours for each day within the time off period.

If the button is not clicked, the table shows the first and the last days only.

Please see the new screenshot attached @GabrielChan1 

<img width="775" alt="Screenshot 2024-06-12 at 10 48 45 AM" src="https://github.com/bluewave-labs/bluewave-hrm/assets/167266851/02052178-f695-4e57-9a75-51b134f57791">
