### ISSUE TITLE
Time off API coding logic

### ISSUE THREAD

**Issue by shidrath** [bluewave-labs/bluewave-hrm#30]
Create a timeoff API to show how the timeoff works in the application. The API should have the following.

- [ ] How the different entities communicate

- [ ] How are requests sent

- [ ] The reasons for timeoff

- [ ] Number of days time off is allowed in a year

**Comment by gorkem-bwl** [comment]
Hi Shidrath. If this issue is complete, can we close it?

**Comment by shidrath** [comment]
Yup We can close it

**Comment by shidrath** [comment]
Finished working on the timeoff logic
