### ISSUE TITLE
Implement text fields, charts, popup modal, tooltips, logos and editor design

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#4]
- [x] Text fields
- [x] Charts
- [x] Popup modal
- [x] Tooltips
- [x] Logos
- [ ] Editor design

<img width="1096" alt="Screen elements 2" src="https://github.com/bluewave-labs/bluewave-hrm/assets/167266851/d45be239-95fc-4213-b9a7-083d3bcb2548">

**Comment by gorkemcetin** [comment]
@ergunesra editor design is not required. You can check with @zaidi201 to see if everything is properly done in this issue.
