### ISSUE TITLE
New logo (big and small)

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#42]
There are two product logos: 

1. The big one is used on the main login screen
2. The small one is used on the dashboard. 

Attaching both of them here. 

![BlueWave HRM_big](https://github.com/bluewave-labs/bluewave-hrm/assets/167266851/e3250c6f-03ef-4d9d-80e3-9b2c1705239d)

![BlueWave HRM_small](https://github.com/bluewave-labs/bluewave-hrm/assets/167266851/9a8897b6-892b-4566-bbaf-39b9de0b4f2c)

**Comment by gorkem-bwl** [comment]
Can you add screenshots for those @GabrielChan1 ?

**Comment by GabrielChan1** [comment]
![large_logo_screenshot](https://github.com/user-attachments/assets/bb07e5b6-93fc-46b3-9dcb-d5fd5cfa6963)
![small_logo_screenshot](https://github.com/user-attachments/assets/e501e2e0-cf55-4090-9ea5-84234a11d4d1)

**Comment by gorkem-bwl** [comment]
@GabrielChan1 the logos should be vice versa (big one should go to the onboarding, and small one should go to dashboard)

**Comment by GabrielChan1** [comment]
I used the small logo for the header and the big logo for the onboarding page. I have no idea why the logo for the header looks bigger

**Comment by gorkem-bwl** [comment]
This is interesting. Can you check uptime manager's code? They have it set up right there -> https://github.com/bluewave-labs/bluewave-uptime/pull/321#discussion_r1676774837

**Comment by gorkem-bwl** [comment]
@GabrielChan1 this is how it looks on the login screen: 
<img width="756" alt="Logo-big" src="https://github.com/user-attachments/assets/c1b1c083-207d-4938-9f64-035027ac1f76">

The logo should be without a background. I believe I sent the one without a bg, but if it doesn't work, I can resend.

**Comment by gorkem-bwl** [comment]
Also, the same goes with this image. Additionally the w x h need to be set correct, making sure it doesn't stretch.

<img width="308" alt="Screenshot 2024-09-01 at 8 59 03 PM" src="https://github.com/user-attachments/assets/b573a919-cb89-473b-b7c6-62de05eecf9b">

**Comment by shidrath** [comment]
Created two sizes of logo using two components
![image](https://github.com/user-attachments/assets/524eadd0-5317-4ade-aa3a-2d5e08e21cbb)
