### ISSUE TITLE
Make sure the permission table is honored in the code

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#77]
@malenacaroline @fazlul-01 @ergunesra @sejunpark2002 Please go over the [Permissions](https://docs.google.com/spreadsheets/d/14uDT2n0oRYgZLE3BzrQIvzmSzGA2C8588glhEPP7ILA/edit?gid=0#gid=0) list to check your code, and make necessary parts of the interface completely invisible/immutable to the manager and/or the employee. If the data is tagged as invisible, it should never be retrieved from the server.

When you are done, click on the task below so @zaidi201 and @olusegunawowole would know this part is finished. This task should be completed before the MVP release.

- [ ] Malena is done on her part.
- [ ] Fazlul is done on his part.
- [x] Esra is done on her part. 
- [ ] Sejun is done on his part.

**Comment by ergunesra** [comment]
Completed to set permissions of myinfo and report pages, and action button
