### ISSUE TITLE
People table must stretch to the right side of the page

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#90]
When I go to People section the width of the table is fixed. It must be stretched all the way to the right.

<img width="981" alt="Screenshot 2024-09-09 at 5 54 41 PM" src="https://github.com/user-attachments/assets/020a33bd-7f46-41b8-8783-944bacaa29c3">

**Comment by gorkem-bwl** [comment]
@olusegunawowole just assigned this to Fazlul. For your information.

**Comment by olusegunawowole** [comment]
Noted
