### ISSUE TITLE
Implement first time employee onboarding screens

### ISSUE THREAD

**Issue by gorkem-bwl** [bluewave-labs/bluewave-hrm#96]
The employee must be onboarded after an account is created. 

[Here is the link to the Figma file](https://www.figma.com/design/GC5nLN8GAXV9NJkzEnDRj3/HRM-app?node-id=6151-15985&t=YlQKye4DRnmR6Eki-1) with descriptions.

**Comment by bolatein** [comment]
Below are the pages to be designed. You may mark them as you completed. 

- [ ] Header with Complete Onboarding button <img width="865" alt="Screenshot 2024-09-27 at 17 25 31" src="https://github.com/user-attachments/assets/12f0666c-b9e0-4782-b329-9650106d74d7">

- [ ] Onboarding 1 - Initial screen <img width="739" alt="Screenshot 2024-09-27 at 17 25 52" src="https://github.com/user-attachments/assets/2fdc99fb-9cf1-42b7-9c41-20ae84143e7d">

- [ ] Onboarding 2 - Videos <img width="739" alt="Screenshot 2024-09-27 at 17 26 18" src="https://github.com/user-attachments/assets/2d7b75a4-2ab1-4952-8162-43e3d7ffb0d2">

- [ ] Onboarding 3 - Readings <img width="704" alt="Screenshot 2024-09-27 at 17 26 31" src="https://github.com/user-attachments/assets/45dee50f-9816-4ce2-a202-93e949c9361f">

- [ ] Onboarding 4 - To-dos <img width="704" alt="Screenshot 2024-09-27 at 17 26 41" src="https://github.com/user-attachments/assets/c9d5e93f-9104-4924-9d03-f46685a345ea">

- [ ] Onboarding 5 - Survey <img width="499" alt="Screenshot 2024-09-27 at 17 27 02" src="https://github.com/user-attachments/assets/eadd0cfb-b4fe-49e6-a69d-08226b1d2fb4">

- [ ] Onboarding 6 - Finished <img width="506" alt="Screenshot 2024-09-27 at 17 27 13" src="https://github.com/user-attachments/assets/5dacb9aa-d188-446a-b2cd-2091ef42d3c6">


For more info, take a look at [the related settings pages](https://www.figma.com/design/GC5nLN8GAXV9NJkzEnDRj3/HRM-app?node-id=6151-15576&t=i3ufH7ZjTRzbn0zy-1).
